### ISSUE TITLE
@Com exception when use disconnect

### ISSUE THREAD

**Issue by ilianAZZ** [UTCAI12/onzzer-server#29]
After killing the client app, the message is : 

```
Server: Server started on port 8001
Server: New socket
Server: received Message<USER_PING>'null'
Server: received Message<USER_PING>'null'
Server: received Message<USER_PING>'null'
Client disconnected: 127.0.0.1
Server: The user does not exist
Exception in thread "Thread-1" java.lang.NullPointerException: Cannot invoke "fr.utc.onzzer.common.dataclass.UserLite.getId()" because "userLite" is null
	at fr.utc.onzzer.server.communication.ServerRequestHandler.userDisconnect(ServerRequestHandler.java:97)
	at fr.utc.onzzer.server.communication.ServerCommunicationController.lambda$new$1(ServerCommunicationController.java:39)
	at fr.utc.onzzer.server.communication.ServerCommunicationController.onMessage(ServerCommunicationController.java:66)
	at fr.utc.onzzer.server.communication.ServerSocketManager.disconnect(ServerSocketManager.java:100)
	at fr.utc.onzzer.server.communication.ServerSocketManager.run(ServerSocketManager.java:94)
```

**Comment by Elydo-dev** [comment]
Fixed : https://github.com/UTCAI12/onzzer-server/commit/43029892821c9f3e7205bdbecd9fc475865bcd7a
